const products = [
  {
    HostRef: 1,
    ParentHostRef: '',
    EppoCode: '1ABEG',
    name: 'Abelia',
    LatinName: 'Abelia',
    Taxonomy:
      'Plantae> Spermatophyta> Angiospermae> Dicotyledones> Dipsacales> Caprifoliaceae',
    COMMON_NAME: {
      ID: [1423, null, null, null, null, null, null, null],
      NAME: ['Abelia (Forster)', '', '', '', '', '', '', '']
    },
    SYNONYM_NAME: {
      ID: [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        ''
      ],
      NAME: [
        'SYNONYM_NAME',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        ''
      ]
    }
  },
  {
    HostRef: 2,
    ParentHostRef: '',
    EppoCode: 'ABEBI',
    LatinName: 'Abelia biflora',
    Taxonomy:
      'Plantae> Spermatophyta> Angiospermae> Dicotyledones> Dipsacales> Caprifoliaceae',
    COMMON_NAME: {
      ID: [1423, null, null, null, null, null, null, null],
      NAME: ['Abelia', '', '', '', '', '', '', '']
    },
    SYNONYM_NAME: {
      ID: [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        ''
      ],
      NAME: [
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        ''
      ]
    }
  },
  {
    HostRef: 3,
    ParentHostRef: '',
    EppoCode: 'ABEBU',
    LatinName: 'Abelia buddleoides',
    Taxonomy:
      'Plantae> Spermatophyta> Angiospermae> Dicotyledones> Dipsacales> Caprifoliaceae',
    COMMON_NAME: {
      ID: [1423, null, null, null, null, null, null, null],
      NAME: ['Abelia', '', '', '', '', '', '', '']
    },
    SYNONYM_NAME: {
      ID: [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        ''
      ],
      NAME: [
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        ''
      ]
    }
  },
  {
    HostRef: 4,
    ParentHostRef: '',
    EppoCode: 'ABECH',
    LatinName: 'Abelia chinensis',
    Taxonomy:
      'Plantae> Spermatophyta> Angiospermae> Dicotyledones> Dipsacales> Caprifoliaceae',
    COMMON_NAME: {
      ID: [1420, null, null, null, null, null, null, null],
      NAME: ['Abelia, chinese', '', '', '', '', '', '', '']
    },
    SYNONYM_NAME: {
      ID: [
        404,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        ''
      ],
      NAME: [
        'Abelia rupestris',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        ''
      ]
    }
  }
]

module.exports = { products }
