const products = [
  {
    HostRef: 1,
    ParentHostRef: '',
    EppoCode: '1ABEG',
    name: 'Abelia',
    LatinName: 'Abelia',
    Taxonomy:
      'Plantae> Spermatophyta> Angiospermae> Dicotyledones> Dipsacales> Caprifoliaceae',
    COMMON_NAME: {
      ID: [1423, null, null, null, null, null, null, null],
      NAME: ['Abelia (Forster)', '', '', '', '', '', '', '']
    },
    SYNONYM_NAME: {
      ID: [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        ''
      ],
      NAME: [
        'SYNONYM_NAME',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        ''
      ]
    }
  }
]

module.exports = { products }
